/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JPanel;

/**
 *
 * @author BBoyp
 */
public class ReservePanel extends javax.swing.JPanel {
    private int piso = 1;
    /**
     * Creates new form ReservePanel
     */
    public ReservePanel() {
        initComponents();
        initStyles();
        showPanel(new RoomFloor(piso));//iniciar en el primer piso
    }

     private void showPanel(JPanel panel){
        panel.setSize(255, 203);
        panel.setLocation(0, 0);
         
        floorPanel.removeAll();
        floorPanel.add(panel,BorderLayout.CENTER);
        floorPanel.revalidate();
        floorPanel.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        floorPanel = new javax.swing.JPanel();
        floorLabel = new javax.swing.JLabel();
        informationTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        informationArea = new javax.swing.JTextArea();
        calendarBG = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        arribaBTN = new javax.swing.JButton();
        abajoBTN = new javax.swing.JButton();

        backGround.setBackground(new java.awt.Color(255, 255, 255));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Reservaciones");

        floorPanel.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout floorPanelLayout = new javax.swing.GroupLayout(floorPanel);
        floorPanel.setLayout(floorPanelLayout);
        floorPanelLayout.setHorizontalGroup(
            floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        floorPanelLayout.setVerticalGroup(
            floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        floorLabel.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        floorLabel.setForeground(new java.awt.Color(0, 0, 0));
        floorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        floorLabel.setText("Piso 1");

        informationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informationTitle.setText("Información");

        informationArea.setEditable(false);
        informationArea.setBackground(new java.awt.Color(255, 255, 255));
        informationArea.setColumns(20);
        informationArea.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        informationArea.setForeground(new java.awt.Color(0, 0, 0));
        informationArea.setRows(5);
        informationArea.setText(" Habitacion A1: Primer piso.\tDisponible\n\n Mascotas: Permitidas.\n\n Servicios: Tina Spa, Accesorios para mascotas, Internet.\n\n Precios: 800$ x Dia.\n");
        jScrollPane1.setViewportView(informationArea);

        jDateChooser1.setDateFormatString("dd/MM/y");
        jDateChooser1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        javax.swing.GroupLayout calendarBGLayout = new javax.swing.GroupLayout(calendarBG);
        calendarBG.setLayout(calendarBGLayout);
        calendarBGLayout.setHorizontalGroup(
            calendarBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calendarBGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calendarBGLayout.setVerticalGroup(
            calendarBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calendarBGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        arribaBTN.setBackground(new java.awt.Color(153, 153, 255));
        arribaBTN.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        arribaBTN.setForeground(new java.awt.Color(0, 0, 0));
        arribaBTN.setText("Arriba");
        arribaBTN.setBorder(null);
        arribaBTN.setBorderPainted(false);
        arribaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arribaBTNActionPerformed(evt);
            }
        });

        abajoBTN.setBackground(new java.awt.Color(153, 153, 255));
        abajoBTN.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        abajoBTN.setForeground(new java.awt.Color(0, 0, 0));
        abajoBTN.setText("Abajo");
        abajoBTN.setBorder(null);
        abajoBTN.setBorderPainted(false);
        abajoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abajoBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backGroundLayout = new javax.swing.GroupLayout(backGround);
        backGround.setLayout(backGroundLayout);
        backGroundLayout.setHorizontalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundLayout.createSequentialGroup()
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backGroundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(calendarBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backGroundLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(arribaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(floorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(abajoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(floorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(backGroundLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backGroundLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(informationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        backGroundLayout.setVerticalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendarBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(floorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floorLabel)
                    .addComponent(arribaBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abajoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void arribaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arribaBTNActionPerformed
        if(piso <5){//limite de pisos normales
            piso = piso+1;
            showPanel(new RoomFloor(piso));
        }else if(piso==5){//piso deluxe
            piso = piso+1;
            showPanel(new RoomFloorDeluxe());
        }
        floorLabel.setText("Piso "+piso);
    }//GEN-LAST:event_arribaBTNActionPerformed

    private void abajoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abajoBTNActionPerformed
        if(piso>1){
            piso = piso-1;
            showPanel(new RoomFloor(piso));
            floorLabel.setText("Piso "+piso);
        }
    }//GEN-LAST:event_abajoBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abajoBTN;
    private javax.swing.JButton arribaBTN;
    private javax.swing.JPanel backGround;
    private javax.swing.JPanel calendarBG;
    private javax.swing.JLabel floorLabel;
    private javax.swing.JPanel floorPanel;
    private javax.swing.JTextArea informationArea;
    private javax.swing.JLabel informationTitle;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private void initStyles() {
    title.putClientProperty( "FlatLaf.style", "font: $h1.font" );
    title.setForeground(Color.black);
    informationTitle.putClientProperty( "FlatLaf.style", "font: $h1.font" );
    informationTitle.setForeground(Color.black);
    
    }
}
