/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author BBoyp
 */
public class ReservePanel extends javax.swing.JPanel {
    /**
     * Creates new form ReservePanel
     */
    public ReservePanel() {
        initComponents();
        initStyles();      
    }

     public void showPanel(JPanel panel){
        panel.setSize(330, 230);
        panel.setLocation(0, 0);
         
        floorPanel.removeAll();
        floorPanel.add(panel,BorderLayout.CENTER);
        floorPanel.revalidate();
        floorPanel.repaint();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        informationArea = new javax.swing.JTextArea();
        backGround = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        floorPanel = new javax.swing.JPanel();
        floorLabel = new javax.swing.JLabel();
        calendarBG = new javax.swing.JPanel();
        reservationDateStart = new com.toedter.calendar.JDateChooser();
        reservationDateEnd = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUpAFloor = new javax.swing.JButton();
        btnDownAFloor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRoom = new javax.swing.JTextField();
        txtRoomPrice = new javax.swing.JTextField();
        chckRoomImpaired = new javax.swing.JCheckBox();
        chckRoomPets = new javax.swing.JCheckBox();
        txtRoomCommodities = new javax.swing.JTextField();
        btnModififyAdmin = new javax.swing.JButton();
        btnReservation = new javax.swing.JButton();
        btnAvailability = new javax.swing.JButton();

        informationArea.setEditable(false);
        informationArea.setBackground(new java.awt.Color(255, 255, 255));
        informationArea.setColumns(20);
        informationArea.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        informationArea.setForeground(new java.awt.Color(0, 0, 0));
        informationArea.setRows(5);
        informationArea.setText(" Habitacion A1: Primer piso.\tDisponible\n\n Mascotas: Permitidas.\n\n Servicios: Tina Spa, Accesorios para mascotas, Internet.\n\n Precios: 800$ x Dia.\n");
        jScrollPane1.setViewportView(informationArea);

        backGround.setBackground(new java.awt.Color(255, 255, 255));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Reservaciones");

        floorPanel.setBackground(new java.awt.Color(102, 204, 255));
        floorPanel.setPreferredSize(new java.awt.Dimension(330, 230));

        javax.swing.GroupLayout floorPanelLayout = new javax.swing.GroupLayout(floorPanel);
        floorPanel.setLayout(floorPanelLayout);
        floorPanelLayout.setHorizontalGroup(
            floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        floorPanelLayout.setVerticalGroup(
            floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        floorLabel.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        floorLabel.setForeground(new java.awt.Color(0, 0, 0));
        floorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        floorLabel.setText("Piso 1");

        reservationDateStart.setDateFormatString("dd/MM/y");
        reservationDateStart.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        reservationDateEnd.setDateFormatString("dd/MM/y");
        reservationDateEnd.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel1.setText("Inicio");

        jLabel2.setText("Fin");

        javax.swing.GroupLayout calendarBGLayout = new javax.swing.GroupLayout(calendarBG);
        calendarBG.setLayout(calendarBGLayout);
        calendarBGLayout.setHorizontalGroup(
            calendarBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calendarBGLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(calendarBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservationDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)))
        );
        calendarBGLayout.setVerticalGroup(
            calendarBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calendarBGLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservationDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservationDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUpAFloor.setBackground(new java.awt.Color(153, 153, 255));
        btnUpAFloor.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUpAFloor.setForeground(new java.awt.Color(0, 0, 0));
        btnUpAFloor.setText("Arriba");
        btnUpAFloor.setBorder(null);
        btnUpAFloor.setBorderPainted(false);

        btnDownAFloor.setBackground(new java.awt.Color(153, 153, 255));
        btnDownAFloor.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDownAFloor.setForeground(new java.awt.Color(0, 0, 0));
        btnDownAFloor.setText("Abajo");
        btnDownAFloor.setBorder(null);
        btnDownAFloor.setBorderPainted(false);

        jLabel3.setText("Cuarto:");

        jLabel4.setText("Precio por día:");

        jLabel5.setText("Apto para mascotas");

        jLabel6.setText("Apto para discapacidades:");

        jLabel7.setText("Servicios:");

        txtRoom.setEditable(false);

        txtRoomPrice.setEditable(false);

        chckRoomImpaired.setEnabled(false);

        chckRoomPets.setEnabled(false);

        txtRoomCommodities.setEditable(false);

        btnModififyAdmin.setBackground(new java.awt.Color(153, 153, 255));
        btnModififyAdmin.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnModififyAdmin.setForeground(new java.awt.Color(0, 0, 0));
        btnModififyAdmin.setText("Modificar");
        btnModififyAdmin.setBorder(null);
        btnModififyAdmin.setBorderPainted(false);

        btnReservation.setBackground(new java.awt.Color(153, 153, 255));
        btnReservation.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnReservation.setForeground(new java.awt.Color(0, 0, 0));
        btnReservation.setText("Reservar");
        btnReservation.setBorder(null);
        btnReservation.setBorderPainted(false);

        btnAvailability.setBackground(new java.awt.Color(153, 153, 255));
        btnAvailability.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAvailability.setForeground(new java.awt.Color(0, 0, 0));
        btnAvailability.setText("Disponibilidad");
        btnAvailability.setBorder(null);
        btnAvailability.setBorderPainted(false);

        javax.swing.GroupLayout backGroundLayout = new javax.swing.GroupLayout(backGround);
        backGround.setLayout(backGroundLayout);
        backGroundLayout.setHorizontalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(floorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReservation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModififyAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(backGroundLayout.createSequentialGroup()
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnUpAFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(floorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDownAFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(calendarBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backGroundLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(backGroundLayout.createSequentialGroup()
                                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(22, 22, 22)
                                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                            .addComponent(txtRoomPrice)))
                                    .addGroup(backGroundLayout.createSequentialGroup()
                                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chckRoomPets)
                                            .addComponent(chckRoomImpaired)))))
                            .addComponent(txtRoomCommodities, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backGroundLayout.setVerticalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtRoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(chckRoomPets))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(chckRoomImpaired))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRoomCommodities, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addComponent(calendarBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGap(8, 8, 8)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floorLabel)
                    .addComponent(btnDownAFloor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpAFloor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addComponent(btnModififyAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReservation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAvailability)))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backGround;
    public javax.swing.JButton btnAvailability;
    public javax.swing.JButton btnDownAFloor;
    public javax.swing.JButton btnModififyAdmin;
    public javax.swing.JButton btnReservation;
    public javax.swing.JButton btnUpAFloor;
    private javax.swing.JPanel calendarBG;
    public javax.swing.JCheckBox chckRoomImpaired;
    public javax.swing.JCheckBox chckRoomPets;
    public javax.swing.JLabel floorLabel;
    private javax.swing.JPanel floorPanel;
    private javax.swing.JTextArea informationArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public com.toedter.calendar.JDateChooser reservationDateEnd;
    public com.toedter.calendar.JDateChooser reservationDateStart;
    private javax.swing.JLabel title;
    public javax.swing.JTextField txtRoom;
    public javax.swing.JTextField txtRoomCommodities;
    public javax.swing.JTextField txtRoomPrice;
    // End of variables declaration//GEN-END:variables

    private void initStyles() {
    title.putClientProperty( "FlatLaf.style", "font: $h1.font" );
    title.setForeground(Color.black);
    
    
    }
}
