/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author BBoyp
 */
public class RoomFloorDeluxe extends javax.swing.JPanel {

    /**
     * Creates new form pisoDeluxe
     */
    public RoomFloorDeluxe() {
        initComponents();
        initStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        floorPanel = new javax.swing.JPanel();
        corridor = new javax.swing.JPanel();
        corridorText = new javax.swing.JLabel();
        roomPanel1 = new javax.swing.JPanel();
        btnDeluxe1 = new javax.swing.JButton();
        roomPanel4 = new javax.swing.JPanel();
        btnDeluxe2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(255, 203));

        floorPanel.setBackground(new java.awt.Color(0, 102, 255));

        corridor.setBackground(new java.awt.Color(255, 255, 153));

        corridorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        corridorText.setText("Corredor");

        javax.swing.GroupLayout corridorLayout = new javax.swing.GroupLayout(corridor);
        corridor.setLayout(corridorLayout);
        corridorLayout.setHorizontalGroup(
            corridorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corridorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(corridorText, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );
        corridorLayout.setVerticalGroup(
            corridorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(corridorText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        roomPanel1.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel1.setPreferredSize(new java.awt.Dimension(66, 66));

        btnDeluxe1.setBackground(new java.awt.Color(102, 255, 102));
        btnDeluxe1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDeluxe1.setForeground(new java.awt.Color(0, 0, 0));
        btnDeluxe1.setText("D1");
        btnDeluxe1.setBorder(null);
        btnDeluxe1.setBorderPainted(false);

        javax.swing.GroupLayout roomPanel1Layout = new javax.swing.GroupLayout(roomPanel1);
        roomPanel1.setLayout(roomPanel1Layout);
        roomPanel1Layout.setHorizontalGroup(
            roomPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDeluxe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roomPanel1Layout.setVerticalGroup(
            roomPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDeluxe1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        roomPanel4.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel4.setPreferredSize(new java.awt.Dimension(66, 66));

        btnDeluxe2.setBackground(new java.awt.Color(102, 255, 102));
        btnDeluxe2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDeluxe2.setForeground(new java.awt.Color(0, 0, 0));
        btnDeluxe2.setText("D2");
        btnDeluxe2.setBorder(null);
        btnDeluxe2.setBorderPainted(false);

        javax.swing.GroupLayout roomPanel4Layout = new javax.swing.GroupLayout(roomPanel4);
        roomPanel4.setLayout(roomPanel4Layout);
        roomPanel4Layout.setHorizontalGroup(
            roomPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDeluxe2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roomPanel4Layout.setVerticalGroup(
            roomPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDeluxe2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout floorPanelLayout = new javax.swing.GroupLayout(floorPanel);
        floorPanel.setLayout(floorPanelLayout);
        floorPanelLayout.setHorizontalGroup(
            floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(corridor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(floorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(roomPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap())
        );
        floorPanelLayout.setVerticalGroup(
            floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roomPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corridor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(floorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(floorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDeluxe1;
    public javax.swing.JButton btnDeluxe2;
    private javax.swing.JPanel corridor;
    private javax.swing.JLabel corridorText;
    private javax.swing.JPanel floorPanel;
    private javax.swing.JPanel roomPanel1;
    private javax.swing.JPanel roomPanel4;
    // End of variables declaration//GEN-END:variables

    private void initStyles() {
    corridorText.putClientProperty( "FlatLaf.style", "font: $large.font" );
    corridorText.setForeground(Color.black);
    }
    
}

