/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author BBoyp
 */
public class RoomFloor extends javax.swing.JPanel {
    private int piso;

    /**
     * Creates new form pisoHabitaciones
     */
    public RoomFloor(int piso) {
        this.piso = piso;
        initComponents();
        initStyles();
        setFloor(this.piso);
    }
    
    private void setFloor(int piso){
        switch (piso) {
            case 1:
                changeRoomText(piso);
                break;
            case 2:
                changeRoomText(piso);
                break;
            case 3:
                changeRoomText(piso);
                break;
            case 4:
                changeRoomText(piso);
                break;
            case 5:
                changeRoomText(piso);
                break;
                
            default:
                JOptionPane.showMessageDialog(null, "Error inesperado x.x");
        }
    }
    
    private void changeRoomText(int piso){
        char letter = (char) (64 + piso);
        roomText1.setText(letter + "1");
        roomText2.setText(letter + "2");
        roomText3.setText(letter + "3");
        roomText4.setText(letter + "4");
        roomText5.setText(letter + "5");
        roomText6.setText(letter + "6");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        floorPanel = new javax.swing.JPanel();
        corridor = new javax.swing.JPanel();
        corridorText = new javax.swing.JLabel();
        roomPanel1 = new javax.swing.JPanel();
        roomText1 = new javax.swing.JLabel();
        roomPanel2 = new javax.swing.JPanel();
        roomText2 = new javax.swing.JLabel();
        roomPanel3 = new javax.swing.JPanel();
        roomText3 = new javax.swing.JLabel();
        roomPanel6 = new javax.swing.JPanel();
        roomText6 = new javax.swing.JLabel();
        roomPanel5 = new javax.swing.JPanel();
        roomText5 = new javax.swing.JLabel();
        roomPanel4 = new javax.swing.JPanel();
        roomText4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(255, 203));

        floorPanel.setBackground(new java.awt.Color(0, 102, 255));

        corridor.setBackground(new java.awt.Color(255, 255, 153));

        corridorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        corridorText.setText("Corredor");

        javax.swing.GroupLayout corridorLayout = new javax.swing.GroupLayout(corridor);
        corridor.setLayout(corridorLayout);
        corridorLayout.setHorizontalGroup(
            corridorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corridorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(corridorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        corridorLayout.setVerticalGroup(
            corridorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(corridorText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        roomPanel1.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel1.setPreferredSize(new java.awt.Dimension(66, 66));

        roomText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomText1.setText("jLabel1");

        javax.swing.GroupLayout roomPanel1Layout = new javax.swing.GroupLayout(roomPanel1);
        roomPanel1.setLayout(roomPanel1Layout);
        roomPanel1Layout.setHorizontalGroup(
            roomPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roomPanel1Layout.setVerticalGroup(
            roomPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomText1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        roomPanel2.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel2.setPreferredSize(new java.awt.Dimension(66, 66));

        roomText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomText2.setText("jLabel1");

        javax.swing.GroupLayout roomPanel2Layout = new javax.swing.GroupLayout(roomPanel2);
        roomPanel2.setLayout(roomPanel2Layout);
        roomPanel2Layout.setHorizontalGroup(
            roomPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomText2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        roomPanel2Layout.setVerticalGroup(
            roomPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        roomPanel3.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel3.setPreferredSize(new java.awt.Dimension(66, 66));

        roomText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomText3.setText("jLabel1");

        javax.swing.GroupLayout roomPanel3Layout = new javax.swing.GroupLayout(roomPanel3);
        roomPanel3.setLayout(roomPanel3Layout);
        roomPanel3Layout.setHorizontalGroup(
            roomPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomText3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        roomPanel3Layout.setVerticalGroup(
            roomPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomText3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        roomPanel6.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel6.setPreferredSize(new java.awt.Dimension(66, 66));

        roomText6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomText6.setText("rom");

        javax.swing.GroupLayout roomPanel6Layout = new javax.swing.GroupLayout(roomPanel6);
        roomPanel6.setLayout(roomPanel6Layout);
        roomPanel6Layout.setHorizontalGroup(
            roomPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomText6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        roomPanel6Layout.setVerticalGroup(
            roomPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomText6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        roomPanel5.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel5.setPreferredSize(new java.awt.Dimension(66, 66));

        roomText5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomText5.setText("jLabel1");

        javax.swing.GroupLayout roomPanel5Layout = new javax.swing.GroupLayout(roomPanel5);
        roomPanel5.setLayout(roomPanel5Layout);
        roomPanel5Layout.setHorizontalGroup(
            roomPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomText5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        roomPanel5Layout.setVerticalGroup(
            roomPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomText5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        roomPanel4.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel4.setPreferredSize(new java.awt.Dimension(66, 66));

        roomText4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomText4.setText("jLabel1");

        javax.swing.GroupLayout roomPanel4Layout = new javax.swing.GroupLayout(roomPanel4);
        roomPanel4.setLayout(roomPanel4Layout);
        roomPanel4Layout.setHorizontalGroup(
            roomPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomText4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );
        roomPanel4Layout.setVerticalGroup(
            roomPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomText4, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout floorPanelLayout = new javax.swing.GroupLayout(floorPanel);
        floorPanel.setLayout(floorPanelLayout);
        floorPanelLayout.setHorizontalGroup(
            floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(corridor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(floorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(floorPanelLayout.createSequentialGroup()
                        .addComponent(roomPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addGap(14, 14, 14)
                        .addComponent(roomPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(roomPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                    .addGroup(floorPanelLayout.createSequentialGroup()
                        .addComponent(roomPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roomPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(roomPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        floorPanelLayout.setVerticalGroup(
            floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(roomPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(roomPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corridor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(roomPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(roomPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(floorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(floorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel corridor;
    private javax.swing.JLabel corridorText;
    private javax.swing.JPanel floorPanel;
    private javax.swing.JPanel roomPanel1;
    private javax.swing.JPanel roomPanel2;
    private javax.swing.JPanel roomPanel3;
    private javax.swing.JPanel roomPanel4;
    private javax.swing.JPanel roomPanel5;
    private javax.swing.JPanel roomPanel6;
    private javax.swing.JLabel roomText1;
    private javax.swing.JLabel roomText2;
    private javax.swing.JLabel roomText3;
    private javax.swing.JLabel roomText4;
    private javax.swing.JLabel roomText5;
    private javax.swing.JLabel roomText6;
    // End of variables declaration//GEN-END:variables

    private void initStyles() {
    corridorText.putClientProperty( "FlatLaf.style", "font: $large.font" );
    corridorText.setForeground(Color.black);
    roomText1.putClientProperty( "FlatLaf.style", "font: $large.font" );
    roomText1.setForeground(Color.black);
    roomText2.putClientProperty( "FlatLaf.style", "font: $large.font" );
    roomText2.setForeground(Color.black);
    roomText3.putClientProperty( "FlatLaf.style", "font: $large.font" );
    roomText3.setForeground(Color.black);
    roomText4.putClientProperty( "FlatLaf.style", "font: $large.font" );
    roomText4.setForeground(Color.black);
    roomText5.putClientProperty( "FlatLaf.style", "font: $large.font" );
    roomText5.setForeground(Color.black);
    roomText6.putClientProperty( "FlatLaf.style", "font: $large.font" );
    roomText6.setForeground(Color.black);
    }
}
