/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author BBoyp
 */
public class RoomFloor extends javax.swing.JPanel {
    private int piso;

    /**
     * Creates new form pisoHabitaciones
     */
    public RoomFloor() {
        initComponents();
        initStyles();
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        floorPanel = new javax.swing.JPanel();
        corridor = new javax.swing.JPanel();
        corridorText = new javax.swing.JLabel();
        roomPanel1 = new javax.swing.JPanel();
        btnRoom1 = new javax.swing.JButton();
        roomPanel2 = new javax.swing.JPanel();
        btnRoom2 = new javax.swing.JButton();
        roomPanel3 = new javax.swing.JPanel();
        btnRoom3 = new javax.swing.JButton();
        roomPanel6 = new javax.swing.JPanel();
        btnRoom6 = new javax.swing.JButton();
        roomPanel5 = new javax.swing.JPanel();
        btnRoom5 = new javax.swing.JButton();
        roomPanel4 = new javax.swing.JPanel();
        btnRoom4 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(255, 203));

        floorPanel.setBackground(new java.awt.Color(0, 102, 255));

        corridor.setBackground(new java.awt.Color(255, 255, 153));

        corridorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        corridorText.setText("Corredor");

        javax.swing.GroupLayout corridorLayout = new javax.swing.GroupLayout(corridor);
        corridor.setLayout(corridorLayout);
        corridorLayout.setHorizontalGroup(
            corridorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corridorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(corridorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        corridorLayout.setVerticalGroup(
            corridorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(corridorText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        roomPanel1.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel1.setPreferredSize(new java.awt.Dimension(66, 66));

        btnRoom1.setText("11");

        javax.swing.GroupLayout roomPanel1Layout = new javax.swing.GroupLayout(roomPanel1);
        roomPanel1.setLayout(roomPanel1Layout);
        roomPanel1Layout.setHorizontalGroup(
            roomPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnRoom1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roomPanel1Layout.setVerticalGroup(
            roomPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(btnRoom1)
                .addGap(28, 28, 28))
        );

        roomPanel2.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel2.setPreferredSize(new java.awt.Dimension(66, 66));

        btnRoom2.setText("12");

        javax.swing.GroupLayout roomPanel2Layout = new javax.swing.GroupLayout(roomPanel2);
        roomPanel2.setLayout(roomPanel2Layout);
        roomPanel2Layout.setHorizontalGroup(
            roomPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnRoom2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roomPanel2Layout.setVerticalGroup(
            roomPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnRoom2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        roomPanel3.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel3.setPreferredSize(new java.awt.Dimension(66, 66));

        btnRoom3.setText("13");

        javax.swing.GroupLayout roomPanel3Layout = new javax.swing.GroupLayout(roomPanel3);
        roomPanel3.setLayout(roomPanel3Layout);
        roomPanel3Layout.setHorizontalGroup(
            roomPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnRoom3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roomPanel3Layout.setVerticalGroup(
            roomPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRoom3)
                .addGap(27, 27, 27))
        );

        roomPanel6.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel6.setPreferredSize(new java.awt.Dimension(66, 66));

        btnRoom6.setText("16");

        javax.swing.GroupLayout roomPanel6Layout = new javax.swing.GroupLayout(roomPanel6);
        roomPanel6.setLayout(roomPanel6Layout);
        roomPanel6Layout.setHorizontalGroup(
            roomPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnRoom6)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        roomPanel6Layout.setVerticalGroup(
            roomPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRoom6)
                .addGap(26, 26, 26))
        );

        roomPanel5.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel5.setPreferredSize(new java.awt.Dimension(66, 66));

        btnRoom5.setText("15");

        javax.swing.GroupLayout roomPanel5Layout = new javax.swing.GroupLayout(roomPanel5);
        roomPanel5.setLayout(roomPanel5Layout);
        roomPanel5Layout.setHorizontalGroup(
            roomPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnRoom5)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        roomPanel5Layout.setVerticalGroup(
            roomPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRoom5)
                .addGap(26, 26, 26))
        );

        roomPanel4.setBackground(new java.awt.Color(102, 255, 102));
        roomPanel4.setPreferredSize(new java.awt.Dimension(66, 66));

        btnRoom4.setText("14");

        javax.swing.GroupLayout roomPanel4Layout = new javax.swing.GroupLayout(roomPanel4);
        roomPanel4.setLayout(roomPanel4Layout);
        roomPanel4Layout.setHorizontalGroup(
            roomPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnRoom4)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        roomPanel4Layout.setVerticalGroup(
            roomPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(btnRoom4)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout floorPanelLayout = new javax.swing.GroupLayout(floorPanel);
        floorPanel.setLayout(floorPanelLayout);
        floorPanelLayout.setHorizontalGroup(
            floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(corridor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(floorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(floorPanelLayout.createSequentialGroup()
                        .addComponent(roomPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addGap(14, 14, 14)
                        .addComponent(roomPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(roomPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addGroup(floorPanelLayout.createSequentialGroup()
                        .addComponent(roomPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roomPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(roomPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        floorPanelLayout.setVerticalGroup(
            floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(roomPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(roomPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corridor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(floorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(roomPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(roomPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(floorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(floorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRoom1;
    public javax.swing.JButton btnRoom2;
    public javax.swing.JButton btnRoom3;
    public javax.swing.JButton btnRoom4;
    public javax.swing.JButton btnRoom5;
    public javax.swing.JButton btnRoom6;
    private javax.swing.JPanel corridor;
    private javax.swing.JLabel corridorText;
    private javax.swing.JPanel floorPanel;
    private javax.swing.JPanel roomPanel1;
    private javax.swing.JPanel roomPanel2;
    private javax.swing.JPanel roomPanel3;
    private javax.swing.JPanel roomPanel4;
    private javax.swing.JPanel roomPanel5;
    private javax.swing.JPanel roomPanel6;
    // End of variables declaration//GEN-END:variables

    private void initStyles() {
    corridorText.putClientProperty( "FlatLaf.style", "font: $large.font" );
    corridorText.setForeground(Color.black);
    }
}
